### ISSUE TITLE
关于新增 mongoose-adapter ？

### ISSUE THREAD

**Issue by szy0syz** [node-casbin/js-sequelize-adapter#2]
你好，我在项目中使用了casbin，并按 “js-sequelize-adapter” 仿了个轮子，我可以加入node-casbin并共享代码吗？

**Comment by hsluoyz** [comment]
Hi @szy0syz , we welcome 3rd-party contributions on adapters or the core library. You can join the QQ group: 825207500 for further discussion.

**Comment by Chalin-Shi** [comment]
> 你好，我在项目中使用了casbin，并按 “js-sequelize-adapter” 仿了个轮子，我可以加入node-casbin并共享代码吗？

有个waterline(no-sql orm)的项目，目前还未完成，阁下有兴趣可以看看能否实现。

**Comment by hsluoyz** [comment]
Hi @szy0syz , we have added your adapter here: https://github.com/casbin/node-casbin#policy-persistence

Let me know if you have any other questions :)

**Comment by szy0syz** [comment]
@Chalin-Shi 好的，我先看看去。主要是项目orm已经在用mognoose了，就不想再使用waterline 🤔
@hsluoyz 非常感谢，已加QQ群~

**Comment by sofapig** [comment]
casbin-mongoose-adapter 您好，您写得这个适配器，是否完成了呢？正好有这个需求，但是我看你的代码上似乎还没有任何东西，只是个说明。我也在开发基于mongodb的项目，感谢这方面分享！

**Comment by hsluoyz** [comment]
@szy0syz Oh, I just forgot that. As @sofapig said, where's the code for the adapter?

**Comment by sofapig** [comment]
@szy0syz expect your code to view!!

**Comment by hsluoyz** [comment]
@sofapig the code is here: https://github.com/szy0syz/casbin-mongoose-adapter

**Comment by sofapig** [comment]
the code is just part of mongodb adapter,it is not  implemented for Casbin adapter interface.

**Comment by hsluoyz** [comment]
@sofapig this issue has been closed and should keep in pease. Please ask questions just in that repo: https://github.com/szy0syz/casbin-mongoose-adapter

**Comment by sofapig** [comment]
OK！
